# ============================================================================
# GitHub Actions Configuration pour SonFusion
# Compilation automatique pour Windows, macOS et Linux
# ============================================================================

name: Build Multi-Platform

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

env:
  APP_VERSION: "2.1"

jobs:
  # ==========================================================================
  # BUILD MACOS
  # ==========================================================================
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        brew install qt ffmpeg
        echo "/opt/homebrew/opt/qt/bin" >> $GITHUB_PATH
    
    - name: Build
      run: |
        qmake son_fusion.pro CONFIG+=release
        make -j$(sysctl -n hw.ncpu)
    
    - name: Create DMG
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir -p deploy_macos
        cp -r son_fusion.app deploy_macos/
        
        # Copier FFmpeg dans le bundle
        cp $(which ffmpeg) deploy_macos/son_fusion.app/Contents/MacOS/
        cp $(which ffprobe) deploy_macos/son_fusion.app/Contents/MacOS/
        chmod +x deploy_macos/son_fusion.app/Contents/MacOS/ffmpeg
        chmod +x deploy_macos/son_fusion.app/Contents/MacOS/ffprobe
        
        # Déployer Qt
        macdeployqt deploy_macos/son_fusion.app -dmg
        
        # Renommer le DMG
        mv deploy_macos/son_fusion.dmg SonFusion_v${{ env.APP_VERSION }}_macOS.dmg
    
    - name: Upload DMG
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v3
      with:
        name: son_fusion-macos-dmg
        path: SonFusion_v${{ env.APP_VERSION }}_macOS.dmg


  # ==========================================================================
  # CREATE RELEASE
  # ==========================================================================
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          son_fusion-macos-dmg/*.dmg
        body: |
          ## SonFusion ${{ github.ref_name }}
          
          Application de fusion et d'édition de fichiers audio.
          
          ### Installation
          
          **macOS:**
          - Ouvrez le fichier .dmg
          - Glissez SonFusion dans Applications
          
          
          ### Dépendances
          
          FFmpeg doit être installé sur votre système.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}